### ISSUE TITLE
Add formatters and, maybe, some linters

### ISSUE THREAD

**Issue by aguschin** [aguschin/art-guide#91]
- Use pre-commit
- Add CI that checks for this and prompts for your fixes

took this https://github.com/iterative/gto/blob/main/.pre-commit-config.yaml and removed all extra:
```
default_language_version:
  python: python3
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-merge-conflict
      - id: check-yaml
        exclude: examples/layouts
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: 'https://github.com/psf/black'
    rev: 23.9.1
    hooks:
      - id: black
  - repo: 'https://github.com/PyCQA/isort'
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
```
